### PR TITLE
Update the build process to catch test and linting errors

### LINKED ISSUE #88: Technical Debt: Run Tests on each PR and Commit
* Add a .travis.yml file to run unit tests and linting

### PR DESCRIPTION
**Pull request by nick-woodward**
* Added a Webpack build process (and ES6 and module support)
* Added Eslint and fixed some errors
* Added an Editorconfig to enforce consistent style across the project
* Moved angular to an external dependency

Resolves #88 

This is a pretty big PR since it includes a formal build process so feel free to take your time with it.
The PRs for the other issues should be quite a bit smaller.

### CODE REVIEW

**Comment by nick-woodward** [comment]
This also creates a coverage file that can be provided to most code coverage services.
https://coveralls.io/github/salte-io/salte-seed

**Comment by aguirrel** [comment]
Awesome PR!  Thanks a lot!

I only have two minor questions:

1.- Why did you remove angular from dependency? This directive is based on it.  I thought adding this dependency was a good practice.

2.- Changes in ng-currency.js doesn't have changes in PR #92.  What do you think about first merging this PR and then PR #92 with this new structure?

**Comment by nick-woodward** [comment]
1. I moved it into the devdependencies so it doesn't force the user into a specific version of angular
You'll notice that other libraries such as [angularfire](https://github.com/firebase/angularfire/blob/master/package.json#L37) which is developed by Google do the same thing.
**Although they do also have it as a peerDependency which I can add as well.**

2. I'm fine with merging this one first! :+1:

**Comment by aguirrel** [comment]
Merged! Thanks a lot!

About dependency, yes please, if you can add it to peerDependency, but just do it in another PR so you don't need to change this one that is really big ;)

**Pull request merged**
