### PR TITLE
Added Attribute Option to Display Zero Values or not

### PR DESCRIPTION
**Pull request by robsecord**
Great Angular Module!
Would like to continue pulling this repo from Bower.io for my project.  Hoping you would like to merge these changes!  Thx in advance!

### CODE REVIEW

**Comment by aguirrel** [comment]
Hi @robsecord ! I will check it. Thanks a lot!

**Comment by aguirrel** [comment]
Please, update to v0.9.3.

**Comment by robsecord** [comment]
Excellent, thx!!

**Comment by aguirrel** [comment]
Hi @robsecord,

I had to revert it becouse it doesn't work as expected. When option DisplayZero is not setted or setted as false should work as always and it gives some strage behaviour.

**Comment by robsecord** [comment]
Ok, no problem..  Been working great for my needs..  Could you explain the
weird behavior?

- RS

On Mon, Mar 7, 2016 at 7:41 AM, Luis Aguirre <notifications@github.com>
wrote:

> Hi @robsecord <https://github.com/robsecord>,
>
> I had to revert it becouse it doesn't work as expected. When option
> DisplayZero is not setted or setted as false should work as always and it
> gives some strage behaviour.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aguirrel/ng-currency/pull/58#issuecomment-193233855>.
>



-- 
- Rob

**Comment by aguirrel** [comment]
Yes! When you add this PR to the code, every shoud work as always (view and model values).  When you set display zeros to false, model gets weird.  And this line should be changed, so if displayZero is undef, default should be false not trrue ;)

scope.displayZeroes = (typeof scope.displayZeroes !== 'undefined')?scope.displayZeroes:true;

to 

scope.displayZeroes = (typeof scope.displayZeroes !== 'undefined')?scope.displayZeroes:false;

Thanks a lot!

**Comment by RodolfoRb** [comment]
when the focus in element set value in 0.00 but if the display-zeroes  = false 
it should validate like

element.on('focus',function(){
var viewValue = ngModel.$$rawModelValue;
if(scope.displayZeroes && (isNaN(viewValue) || viewValue === '' || viewValue == null))

**Comment by aguirrel** [comment]
Hi @RodolfoRb yes it solve one of the problems.  Main problem here is that display-zeroes should be false as default and when false directive should work 100% as always and we can't reach this point. ;)

**Pull request merged**
