### PR TITLE
fix: debouncing values causes the new value to get overridden with the old value

### LINKED ISSUE #130: Update on debounce does not work
### Description
The input is not formatted on debounce, only on blur.  

### Expected outcome

50000 does not turn into $50,000 on debounce.

### Actual outcome

50000 should turn into $50,000 on debounce.

### PR DESCRIPTION
**Pull request by cecilia-sanare**
- This was rendering debounce useless since it would override the modelValue

closes #130

### CODE REVIEW

**Comment by nick-woodward** [comment]
@holtc can you verify that this fixes your issue?

**Comment by holtc** [comment]
Do I just pull the latest to check the fix?

**Comment by nick-woodward** [comment]
Unfortunately there isn't really an easy way.

**The best way that I know if is the following:**

- Clone the Repo
- Checkout `support-debounce`
- Run `npm run build:prod`
- Copy the `dist` directory over to your `node_modules/ng-currency` directory in your project

**Comment by holtc** [comment]
Is there any way to push up the built .js file so I can copy that?

**Comment by nick-woodward** [comment]
Sure, here's the built code.

**[ng-currency.zip](https://github.com/aguirrel/ng-currency/files/851602/ng-currency.zip)**

**Comment by holtc** [comment]
Thanks!  Still is not working with debounce = 200

**Comment by nick-woodward** [comment]
Hmm, seems to work for me.

### Live Demo

https://jsbin.com/vuzecut/1/edit?html,js,output

**Comment by holtc** [comment]
It is only updating the shown value on blur still, not on the actual debounce.

**Comment by nick-woodward** [comment]
So you want it to delay changing the visual value from "50000,00" to "$50.000,00" until the debounce has finished?

**Comment by holtc** [comment]
Yes, since that is when the model updates. That way, if denounce is set low
enough, it will appear as if the value is being formatted in realtime

**Comment by nick-woodward** [comment]
@holtc Ah, I think I understand now. 

You effectively want it to display the formatted value while the user still has the input selected.

I think we should separate these two issues. Since what you're suggesting would 
be a fundamental change to the library that requires discussion.

This fixes an issue where `ng-currency` was preventing model updates when debounce was present.

@aguirrel What are your thoughts on this?

**Comment by holtc** [comment]
I don't think it has anything to do with still selected. Just whenever the
debounce event occurs it should reformat, since that is when the model
value is updated.

**Comment by nick-woodward** [comment]
Hmm, stills seems to be a fundamental change since we don't ever 
display the formatted value until the user deselects the field.

However with what you're suggesting debounce would be the only case 
where that formatted value could display while the field is selected.

**Comment by holtc** [comment]
Gotcha okay. I remember modifying an older version to accomplish this
functionality. It may not have been on denounce, it may have been on
immediate update

**Comment by nick-woodward** [comment]
I'm going to merge this since it does fix an issue with `ng-currency` overriding 
the model value on debounce, but feel free to open a separate issue if you feel like 
theirs some functionality missing from `ng-currency` that you'd like us to add!

**Pull request merged**
