### PR TITLE
Displaying the real value on focus now display the locales decimal separator rather then always displaying '.'

### LINKED ISSUE #103: Decimal separator always "."
### Description

When focusing the field, the decimal separator is always a ".". Should be possible to make it "," for countries that uses comma for countries using that format.

### Expected outcome

Comma instead of a dot when applicable :) Either automatic or as a configuration (globally preferred if so). Using a combo of `angular-locale` and `angular-dynamic-locale` package it should be possible to load the thousands separator dynamically (it worked like that pre 0.9.x).

### Actual outcome

Always a dot.

### Live Demo

N/A

### Steps to reproduce

1. Enter field to edit
2. See issue :)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

### PR DESCRIPTION
**Pull request by cecilia-sanare**
This will end up being a major/minor version bump if it gets merged since it will be modifying how existing functionality works.

[Live Demo](https://jsbin.com/coxiwibedi/edit?html,output) (This launches with the input focused)

Resolves #103

### CODE REVIEW

**Comment by houmark** [comment]
LGTM! +1 from testing advanced setup. See my comment on #103.

**Comment by nick-woodward** [comment]
@aguirrel Can you look at this when you get the chance?

**Comment by aguirrel** [comment]
Hi @nick-woodward and @houmark .  

I really love recovering this option, is much more friendly.  I think this should default behavior and add some option parameter to use dot (.) for those who use only numeric pad to input data.

What do you think about this new option?

**Comment by nick-woodward** [comment]
@aguirrel 
I believe you can still enter data with dots if you want to due to how well your parsing logic was written.
If you're modifying a field it'll obviously have the locale specific decimal separator. 
However I doubt the user would modify the decimal separator at that point anyways.

I'm game to add a `use-model-value` binding, but I'm not entirely sure it would be used.

**Comment by aguirrel** [comment]
Yes! It works like a charm! Merged! Thanks a lot!

**Comment by houmark** [comment]
Nice to see this merged! Maybe this should merit a new release? I'd suggest v1.1...

**Comment by aguirrel** [comment]
Yes, @nick-woodward is implementing issue "#104 Semantic Release".  

@nick-woodward , do you think is better to create a new release before or after #104 is done?

**Comment by nick-woodward** [comment]
@aguirrel v1.1.0 already contains these changes,

**Pull request merged**
